---
engine_version: 0.2.59
file_version: 2022-02-06 20:58:27.268413000 Z
resources:
- name: user
  preferences:
    actions:
    - name: hello
      display_name: Hello
      action_type: method
      preferences:
        method_name: say_hello
    - name: bye_bye
      display_name: ByeBye
      action_type: method
      preferences:
        method_name: say_bye
  updated_at: 2022-02-06 20:58:27.236611000 +00:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2022-02-06 20:02:13.867217000 +00:00
- key: resources.user.actions.order
  value:
  - create
  - edit
  - remove
  - hello
  - bye_bye
  updated_at: 2022-02-06 20:58:27.268413000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2022-02-06 20:02:13.885857000 +00:00
